### ISSUE TITLE
CMC 내부 DTO Convention

### ISSUE THREAD

**Issue by 60jong** [KU-CMC/CMC_Server#19]
# DTO Convention
`DTO : Data Transfer Object`
먼저 DTO는 데이터 전송 객체로 단순히 데이터를 전달하는 역할을 하는 객체
***
제가 생각하는 객체간의 의존성 개념을 기준으로 정리하였습니다. 모든 피드백 / 리뷰를 환영합니다.

네 가지 `why using` / `when to use` / `how to name` / `where to put` 파트로 나누어 정리하겠습니다.

## Why using
- 실수 유발 방지 + 의도치 않은 로직 방지
  ```
  Entity의 값 수정이 반영되려면 Transaction 안에 있어야 하기에, 
  Transaction을 벗어난 Entity에서 값을 get하는 것은 물론 문제가 생기지 않을 수 있다고 생각합니다.

  하지만 이 또한 `실수`할 가능성이 높다고 생각이 듭니다. 해당 Entity가 하나의 Transaction 안에서
  돌아다녀 의도치 않은 수정을 유발할 수도 있다고 생각합니다.
  
  핵심은 "실수 X" 와 "의도한 대로 작동하게"입니다.
  ```

- 가독성
  - 메서드는 파라미터를 받을 수 있는데 만약 파라미터가 너무 많아지면 가독성을 떨어트릴 수도 있다고 생각합니다.
  - caller가 파라미터 순서도 헷갈리면 실수할 가능성도 O

- 객체 간 의존성 분리
  ```  
  객체 B가 객체 C의 메서드를 호출할 때, 파라미터로 `a`라는 객체를 넘긴다고 가정하겠습니다.
  그런데 a는 B`가 객체 A로부터 전달받은 객체입니다.
 
  A -> B.foo(a);
  B -> c.bar(a);

  이 상황은 객체 B와 C가 A에게 의존하도록 설계 되어있습니다. 
  만약 파라미터 객체인 a가 변하게 된다면...(a.getNumber() -> a.getCount() 로 메서드명 변경) 
  B와 C 모두 메서드 내부에서 변하게 된 a를 반영해야 할 것입니다. 
  
  이렇게 a를 그대로 사용하는 객체가 많고, 이들 모두 같은 객체를 공유한다면 수정할 것은 산더미...겠죠... 
  (a가 비즈니스 로직 상 변할 가능성이 없다면 그대로 전달되는 것을 고려해볼만 하다고 생각합니다. 
     예) member의 bodyinfo에서 부위별 사이즈)

  하지만 그렇지 않다면 이러한 의존성을 제거해야 합니다. -> 각 객체가 받고 싶은 데이터를 주도적으로 표현해야 함.

  B객체는 파라미터로 b를, C객체는 파라미터로 c를... (b -> c로 바꾸는 과정은 C를 부르고 싶다면 B가 해야겠죠)
  ```
## When to use

객체 간 협력하는 예시인.... 주로 Controller / Service / Repository에서!!!

## How to name

이러한 방식은 어떨까요
- Controller는 request와 response를 담당하니 
  `suffix = requset / response`
  `Http Method`도 포함시킨다면?
  -> `도메인명 ` + `Http Method` + `suffix` -> `Category` + `Post` + `Request`

- Service는 `도메인명` + 검색조건`Conditions` / 파라미터`Params` 등등...

- Repository는 JPA를 사용하니 Entity가 이동하는 것이 좋겠고요.

## Where to put
_사실 저장할 패키지 관련해서 Issue 작성하려고 했는데 길어졌네요ㅜㅋㅋㅋㅋ 죄송합니다._

위 내용들을 종합해보면 DTO가 필요한 부분은
- Controller가 요청 / 응답 처리할 때
- Service가 메서드를 정의할 때
- 불변 객체
  - 파라미터가 많은 메서드를 호출할 때
  - 혹은 내용이 불변할 객체

같습니다. 따라서 이들에 대한 패키지는

- Controller가 요청 / 응답 처리할 때  -> `web/controller/dto/도메인`
- Service가 메서드를 정의할 때           -> `service/dto/도메인`
- 불변 객체                                       -> `common/dto/도메인`

**Comment by lcj1204** [comment]
몇가지 의문점이 있어서 리뷰 남깁니다!
우선 고생했습니다.. 중요한 부분 디테일 하게 고민 해주셨네요. 정말 고맙습니다! 오늘도 많이 배워갑니다 😄 

### 1. Why Using
- "하나의 Transaction 안" 이라는게 결국에 Service 의 하나의 메소드(readOnly 제외)를 의미하는것이 아닌가요? 맞다면, 이 하나의 메소드 안에서 Entity 가 돌아 다닐때 의도치 않은 실수가 예상이 안되는데 예시 하나만 들어주실 수 있으실까용

### 2. How To Name
- 너무 좋습니다! 다만 하나의 도메인에 대해 같은 Http Method 가 여러개 생길 수 있는데 이러한 경우엔 어떻게 나누는게 좋을까요?
- 제안) 동사(행위)나 대상을 추가하는건 어떨까요? `도메인명`  + `Http Method` + `action or target` + `suffix` 
간단 정보 조회 -> `Designer` + `Get` + `Info` + `Response`
상세 정보 조회 -> `Designer` + `Get` + `Detail` + `Response`

회원가입 -> `Designer` + `Post` + `signup` + `Request`
로그인 -> `Designer` + `Post` + `signin` + `Request`

- Service 단의 Dto 는 잘 이해가 안갑니다 ㅠ 검색 뿐만 아니라 , 생성, 수정, 삭제 등 다양한 경우가 생길 것 같은데 그런경우엔 `검색 조건` 에 해당하는 부분에 어떤것을 넣어야 하나요?

 ### 3. Where To Put
- Service 단 처럼 Controller 패키지 내에 dto 패키지를 포함 시키지 않고, Web 패키지에 포함 시킨 이유는 무엇인가요?

**Comment by 60jong** [comment]
피드백 감사합니다!!
피드백 읽어보니 좋은 인사이트가 많은 것 같습니다 :) 의문으로 남겨주신 점에 대해 제 의견을 첨언하겠습니다.

제가 인사이트 얻었던 게시글인데 발췌독해보셔도 좋을 것 같아요!! https://techblog.woowahan.com/2711/ 

### 1. Entity가 완전하지 않은 상태로 돌아다니는 것에 대한 실수
두 가지 이유 때문에 DTO를 사용한다고 생각합니다.
- Controller 단에서 Entity를 다루는 것 : Controller는 Business와 관련된 내용인 Entity를 아는 것은 Controller의 역할을 넘어선다고 생각합니다. (+ Controller 단에서는 `영속성 컨텍스트`의 관리가 없기에, `id`가 적용된 Entity도 아닙니다.)

- 말씀해주신 실수의 예시 같은 부분은 이러한 Controller 단에서 Entity를 다룰 때라고 생각합니다.
  ```Controller에서 한 Entity를 만들어 Service Layer에게 넘겨줄 때, 
  Controller단에서 설정한 필드 값은 Service단에서 검증하지 않는 이상 
  그대로 Entity의 필드로 등록될 것입니다. 
  ( Controller단은 request의 내용으로 Entity 생성... But Serivice는 특정 필드 
  값 수정하지 않았지만 Controller에서 수정한 값이 그대로 저장됨 ) <-- 실수 유발 여지
  ```

이러한 두 가지 이유로 (메인은 Controller의 역할 / Service의 역할 분리) DTO 사용이 지향된다고 생각합니다.

### 2. 제안해주신 Naming
창재님 제안(중간에 도메인에 대한 행위 추가)이 좋은 것 같습니다.

DTO는 비즈니스 로직이 아닌지라 `클래스명만 보고도 사용처를 알아야 한다`라는 생각으로 건의 드렸었는데,
저 방식이 가장 좋은 것 같습니다!! 저렇게 명명하도록 하겠습니다.

그리고 굳이 저런 Convention이 아니더라도 `클래스명만 보고도 사용처를 알아야 한다`를 충족시킬 수 있다면
얼마든지 변형해도 좋을 것 같습니다!


### 3. Service 단의 DTO
명확한 기준 없이 말씀드린 것 같네요. 죄송합니다. 

제가 Service단의 DTO를 만들 때 명확한 기준없이 만들었던 것 같습니다.

만약 Service의 메서드가 DTO를 필요로 할 경우 (`주로 파라미터가 너무 많은 경우`) 
파라미터들의 특성을 잘 반영할 수 있는 + `클래스명만 보고도 사용처를 알아야 한다` 면 크게 Convention이 필요없을 것 같습니다!

!! 그런데 주로 Service단에서 DTO를 만드는 경우는 Return 값인 경우가 많은 것 같습니다.
이 경우에는 `도메인` + `web 응답 로직`으로 적는 것 같습니다.
- Member 간단 조회의 경우 -> `MemberInfo`

- Member 상세 조회의 경우 -> `MemberDetail`

이렇게요!!

```
참 이 부분(Serivce의 Return 타입)에서 많은 생각을 하게 되는데
누구는 Controller가 응답할 ResponseDTO를 그대로 return하는 경우도 있어서

정답은 없어보입니다...
```
### 4. web 패키지
백엔드의 시스템 아키텍쳐는 그림처럼
<img width="624" alt="84589073-2a22a700-ae67-11ea-99c8-4ce1086150df" src="https://github.com/KU-CMC/CMC_Server/assets/93924890/10b3a801-2e45-4556-9295-d2e2370b48d1">
web / service / repository layer로 구분되기에

Controller 패키지를 web패키지 아래로 지정하게 되었습니다!!

**Comment by lcj1204** [comment]
모두 이해했습니다 ㅎ ㅎ 상세한 피드백 너무 감사합니다 👏 

참고하여 모두 반영하도록 하겠습니다!!
