### ISSUE TITLE
제작 요청 도메인인 ProductionRequest 관련 이슈

### ISSUE THREAD

**Issue by lcj1204** [KU-CMC/CMC_Server#20]
ProductionRequest 도메인 명에 몇가지 문제점이 있습니다!

1. 도메인명이 너무 길어 가독성이 떨어집니다. DTO 를 생성하게 될 경우 `ProductionRequestPostRegisterRequest` 처럼 매우 길어집니다!
2. 요청 Dto 의 경우 `ProductionRequestPostRegisterRequest` 처럼 작성하게 되면 `Request` 가 두번 들어가 혼동이 될 수 있을 것 같습니다.
3. 앞단어 Production 도 Product 와 비슷해 한눈에 알아보기 힘들것 같습니다.

따라서 다음과 같이 도메인 명 변경을 제안합니다!

`ProductionRequest` ->  `Custom`

**Comment by 60jong** [comment]
최대한 이름을 줄이지 않는 것이 좋다고는 알고 있으나, 그게 위 상황처럼 가독성을 매우 떨어뜨리는 경우에는

변경이 필요해보입니다!!

`ProductionRequset` -> `Custom`이 가장 좋은 변경 같습니다 ㅎㅎ 

다음 PR올려주실 때 반영 부탁드립니다!!

**Comment by lcj1204** [comment]
확인했습니다!
